[32m2023-11-14 16:00:29 -0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB_0 - 20a1fbb6-b7a0-48c3-b405-c4ef7d1097b0 - 82305 - LOGS_CAPTURED - Started capturing logs in process (pid: 82305).
[32m2023-11-14 16:00:29 -0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB_0 - 20a1fbb6-b7a0-48c3-b405-c4ef7d1097b0 - 82305 - matching - STEP_START - Started execution of step "matching".
[32m2023-11-14 16:00:29 -0800[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB_0 - 20a1fbb6-b7a0-48c3-b405-c4ef7d1097b0 - 82305 - matching - STEP_FAILURE - Execution of step "matching" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "matching"::

NameError: name 'parser' is not defined

Stack Trace:
  File "/Users/zhangyan/myenv/lib/python3.9/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/zhangyan/myenv/lib/python3.9/site-packages/dagster/_utils/__init__.py", line 443, in iterate_with_context
    next_output = next(iterator)
  File "/Users/zhangyan/myenv/lib/python3.9/site-packages/dagster/_core/execution/plan/compute_generator.py", line 132, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/Users/zhangyan/myenv/lib/python3.9/site-packages/dagster/_core/execution/plan/compute_generator.py", line 126, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/Users/zhangyan/myenv/tabby-data-pipeline/tabby_data_pipeline/assets.py", line 60, in matching
    analyze.analyze(model, language, file)
  File "/Users/zhangyan/myenv/tabby-data-pipeline/tabby_data_pipeline/analyze.py", line 67, in analyze
    tabby_eval["first_statement_prediction"] = postprocess_code_lines(tabby_eval["raw_prompt"], prediction, parser, language)
[0m
